name: Build and Release

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24.3'

      - name: Build linux amd64
        run: GOOS=linux GOARCH=amd64 go build -o dist/anigarden-linux-amd .

      - name: Build linux arm64
        run: GOOS=linux GOARCH=arm64 go build -o dist/anigarden-linux-arm .

      - name: Build macos arm64
        run: GOOS=darwin GOARCH=arm64 go build -o dist/anigarden-macos-arm .

      - name: Upload Linux amd64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: anigarden-linux-amd
          path: dist/anigarden-linux-amd

      - name: Upload Linux arm64 artifact
        uses: actions/upload-artifact@v4
        with:
          name: anigarden-linux-arm
          path: dist/anigarden-linux-arm

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: anigarden-macos-arm
          path: dist/anigarden-macos-arm

  commit-dist:
    needs: build 
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download Linux amd64 artifact
        uses: actions/download-artifact@v4
        with:
          name: anigarden-linux-amd
          path: dist

      - name: Download Linux arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: anigarden-linux-arm
          path: dist

      - name: Download macOS arm64 artifact
        uses: actions/download-artifact@v4
        with:
          name: anigarden-macos-arm
          path: dist

      - name: Set up Git user
        run: |
          git config --global user.email "fat-bot@fynjirby.dev"
          git config --global user.name "FAT Bot"

      - name: Commit and push dist binaries
        run: |
          git fetch origin master
          git checkout master
          git add -A dist/
          git commit -m "FAT Bot: uploaded dist binaries [skip ci]" || echo "No changes to commit"
          git push origin master
